image_dir: "data/v1/scans"
prompts_dir: "data/v1/prompts"
text_embeddings_dir: "data/v1/text_embeddings"
img_embeddings_dir: "data/v1/image_latents"
data_type: "skybox_images"
seed: 0
skybox_indices: 6
vx: [-90, 270, 0, 90, 180, -90]
vy: [90, 0, 0, 0, 0, -90]
fov: 90
rot: 45
resolution: 512
crop_size: 512